Repository OoLunar/HyperSharp, pull requests merged in 2023-08, with the labels that each got.

#1 silly generator
  HyperSharp.sln
  gen/Constants.cs
  gen/ConstructorModel.cs
  gen/HyperSharp.Generators.csproj
  gen/NamespaceSymbolExtensions.cs
  gen/StatusCreationEmitter.cs
  gen/StatusCreationGenerator.cs
  gen/TypeSymbolExtensions.cs
  src/HyperSharp/HyperSharp.csproj
  src/HyperSharp/Protocol/HyperStatus.cs
Labels: enhancement

#2 add docs
  .github/docs.yml
  .gitignore
  docs/.gitignore
  docs/api/.gitignore
  docs/api/index.md
  docs/articles/intro.md
  docs/articles/toc.yml
  docs/docfx.json
  docs/index.md
  docs/toc.yml
Labels: documentation, enhancement

#3 the simplest fix
  docs/docfx.json
Labels: documentation, enhancement

#4 even simpler fix
  .github/workflows/docs.yml
Labels: documentation, duplicate, enhancement

#5 Switch to MIT license
  LICENSE
Labels: documentation, enhancement, help wanted
